num = 4567
Alafim = num//1000
Meot = num//100%10
Asarot = num//10%10
Ahadot = num%10
print("Alafim = " + str(Alafim) +
      '\n' + 'Meot = ' + str(Meot) +
      '\n' + 'Asarot = ' + str(Asarot) +
      '\n' + 'Ahadot = ' + str(Ahadot))
